### ISSUE TITLE
FSK mode breaks the satellite

### ISSUE THREAD

**Issue by AdamElsharhawy** [proveskit/circuitpy_flight_software#21]
While messing around with the CubeSat we found that if you try to send a string with CW it throws an error, following this error it does not switch back to the proper mode when trying to send LoRa packets ultimately breaking the satellite's LoRa transmission abilities until a restart has happened. 
I have linked a screen recording of our testing / replication of this issue: 
https://www.youtube.com/watch?v=-iUtgulR56o

_Timestamp/description:_
- 1:27 some LoRa test packets were sent
![image](https://github.com/user-attachments/assets/aa0df1c7-6765-449a-9c27-319c1f3085a1)
- 1:40 cw test packets were sent to try and replicate the issue
![image](https://github.com/user-attachments/assets/dbbe8942-3d55-4322-ae88-d5e64a5e8009)
- 1:46 we were able to send LoRa packets normally
![image](https://github.com/user-attachments/assets/5b4ba35f-99a0-4169-bd78-24197a59e999)
- 4:12 after some thinking we tried sending the string with CW and were then given the error
![image](https://github.com/user-attachments/assets/e3a38b58-64e9-48ab-aede-8fa55e4ef835)
- 4:25 through 4:34 you can see that it has broken and is not switching back to the right mode when trying to send LoRa packets again
![image](https://github.com/user-attachments/assets/2e558cd0-7b47-4aae-a651-df049141fedf)

**Comment by Mikefly123** [comment]
This was fixed in this pull request! 

https://github.com/proveskit/circuitpy_flight_software/pull/36
