### ISSUE TITLE
Flight Controller Uptime Overflow

### ISSUE THREAD

**Issue by Mikefly123** [proveskit/circuitpy_flight_software#48]
Didn't have a clock running but we see an uptime overflow on the flight controller board. This is a problem, the board was on for maybe only 15 minutes. 
![image](https://github.com/user-attachments/assets/f920cb89-cc4e-4939-a4ee-a6efe2c3fd8f)

**Comment by blakejameson** [comment]
Yesterday, I tried reproducing the issue on the Orpheus branch and was unable to reproduce the overflow. Was this issue addressed?

**Comment by Mikefly123** [comment]
We have also been unable to replicate this issue. It is possible that it was a one off variance with that board. Maybe an issue with the internal clock? 

I am going to close this issue for now. Maybe someday we will encounter it again.
